---
abstract: 'method and function declarations with signatures and no source filter'
author:
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  Module::Build: 0.26
  Test::Builder: 0.82
  Test::More: 0.82
  Test::Warn: 0.10
configure_requires:
  Module::Build: 0.26
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Method-Signatures
provides:
  Method::Signatures:
    file: lib/Method/Signatures.pm
    version: 20110322.0027_001
  Method::Signatures::Parser:
    file: lib/Method/Signatures/Parser.pm
    version: 0
requires:
  Const::Fast: 0.006
  Data::Alias: 1.08
  Devel::BeginLift: 0.001001
  Devel::Declare::MethodInstaller::Simple: 0.003003
  PPI: 1.203
  perl: v5.8.1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Method-Signatures
  license: http://dev.perl.org/licenses/
  repository: https://github.com/schwern/method-signatures/tree
version: 20110322.0027_001
