---
name: Method-Signatures
version: 0.02
author:
  - 'Michael G Schwern <schwern@pobox.com>'
abstract: method declarations with prototypes and without using a source filter
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Method-Signatures
  license: http://dev.perl.org/licenses/
  repository: http://svn.schwern.org/svn/CPAN/Method-Signatures
requires:
  Devel::Declare: 0.001006
  Test::More: 0.62
provides:
  Method::Signatures:
    file: lib/Method/Signatures.pm
    version: 0.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
